# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MADAOPost' do

end

target 'MADAOPostTests' do

end

target 'MADAOPostUITests' do

end

pod 'YTKNetwork'
pod 'MagicalRecord'
pod 'Masonry'
pod 'SWTableViewCell'